### ISSUE TITLE
Can it work on ns or ps4 or just pc?

### ISSUE THREAD

**Issue by MarStarck** [LuiCat/ArduinoTaikoController#1]

**Comment by LuiCat** [comment]
Hi MarStarck, this sketch only works for PC, as only keyboard input is generated. For NS/PS4 support, you would need an extra circuit for imitating the console controllers. However, I believe that you can use an additional library ([ArduinoJoystickLibrary](https://github.com/MHeironimus/ArduinoJoystickLibrary)) in generating HID joystick inputs and use a PS4/NS converter to port the signal to your console device. Not sure if this would cause latency on input signals.

**Comment by LuiCat** [comment]
Hi, a bump on this. I'm now working at NS support for this one. It seems that the descriptor provided in [progmem/Switch-Fightstick](https://github.com/progmem/Switch-Fightstick) works for Arduino Micro, and I will dig into mimicking a taiko controller with the same idea. I will update it here or in another repository when there is progress.

**Comment by xia0ming** [comment]
Hi, is there any progress at PS4 support? I did tons of research about emulating or making a PS4 controller with Arduino but no result yet

**Comment by LuiCat** [comment]
@xia0ming Sorry, but I won't implement PS4 for this project. You can try to use a converter to achieve this.

To be reasonable, it's basically impossible to mimick a PS4 controller without help of hardware other than an Arduino Leonardo/Micro. Those brand-specific controllers does something more than USB HID and couldn't be arbitrarily implemented with the chip, atmega32u4, on the Arduino.

On the other side, Nintendo Switch simply allows using a certain subset of HID joysticks. It means that if carefully enough, any atmega32u4 Arduino can do for NS.
