### ISSUE TITLE
can't compile or upload

### ISSUE THREAD

**Issue by Mrpunklord** [LuiCat/ArduinoTaikoController#12]
hey, i've some trouble i can't compile or uploading the script bacause of that: 

Arduino : 1.8.19 (Windows 10), Carte : "Arduino Leonardo"

E:\telechargement\ArduinoTaikoController-master\ArduinoTaikoController-master\taiko_controller\Joystick.cpp: In constructor 'Joystick_::Joystick_()':

Joystick.cpp:78:8: error: 'class HID_' has no member named 'PrependDescriptor'; did you mean 'AppendDescriptor'?

  HID().PrependDescriptor(&node); // This descriptor need to be the first one so that the device can be recognized by Switch

        ^~~~~~~~~~~~~~~~~

        AppendDescriptor

E:\telechargement\ArduinoTaikoController-master\ArduinoTaikoController-master\taiko_controller\Joystick.cpp: In member function 'void Joystick_::sendState()':

Joystick.cpp:83:8: error: 'class HID_' has no member named 'SendRaw'; did you mean 'SendReport'?

  HID().SendRaw(this, 8); // No sending report ID. Switch doesn't deal with that properly.

        ^~~~~~~

        SendReport

exit status 1

'class HID_' has no member named 'PrependDescriptor'; did you mean 'AppendDescriptor'?

and when i don't have "Nintendo switch controller" choice on board menu

**Comment by Mrpunklord** [comment]
nevermind , i've delete switch part

**Comment by LuiCat** [comment]
The setup for Nintendo Switch is tedious. However, I believe there might be an easier way to do this. Might be able to come back and look into it in the future.

**Comment by LuiCat** [comment]
Refer to #10 .
