### ISSUE TITLE
What to do with "taiko_controller" file / Where to put it

### ISSUE THREAD

**Issue by KuruUwU** [LuiCat/ArduinoTaikoController#18]
(doing the NS version)
While I tried to upload the code that I copypasted from taiko_controller file named "taiko_controller.ino" in arduino IDE into my Leonardo, I got a compilation error where it said "AnalogReadNow.h: No such file or directory"
![Output](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/7243489a-5ed7-4f06-83ff-0e5961e7055c)
I then looked around the taiko_controller file on github and found the files that I assume that I needed to download
![taiko_controller file](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/1139d906-259f-43bc-9abf-5e2abe75554e)
Now the real question is... now that I downloaded the 5 files, where do I like put these files? Or do I just copypaste the code contents from inside each of the .cpp and .h files and put them into arduino IDE where the .ino code is already in?

(This is my first project that includes any arduino or any electrical hardward stuff so sorry if this question is like beginner questions)

**Comment by Derpwi** [comment]
Ok so decided to experiment around and just followed the directory to then I have dragged the .cpp and .h files into where the code is saved on
![File looks](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/87684767-39ea-4156-b4dc-61088b9c9c25)
now the the problem

**Comment by KuruUwU** [comment]
Ok so decided to experiment around and just followed the directory to then I have dragged the .cpp and .h files into where the code is saved on
![File looks](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/0837c081-2ee8-486d-afeb-8241f7d4208b)
now the problem just like #16 is occuring where it said (Property 'upload.tool.serial' is undefined)
![Output2](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/843bdd0b-320d-4cfa-a73b-501edadf62c3)

**Comment by KuruUwU** [comment]
Wait i think i cracked the code (kekw)

in the location where we would place the "boards.txt"
inside the text you would see "leonardo.upload.tool=avrdude" and "ns_con.upload.tool=avrdude" add the word "serial" at the end of tool

leonardo.upload.tool=avrdude -> leonardo.upload.tool.serial=avrdude
ns_con.upload.tool=avrdude -> ns_con.upload.tool.serial=avrdude

(if you use a promicro, change it on the promicro one instead I assume ex. pro.upload.tool.serial=avrdude)

after i done that i got a differnt message

![fixed](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/d86b16f9-9797-4e55-b398-754de19ef150)
![done uploading](https://github.com/LuiCat/ArduinoTaikoController/assets/47728628/000af81c-1ce9-44af-b0df-5b33e95cb728)

I havent actually attached the Piezo sensors yet to test it out but my hope to get it working has gone up a bit
