### ISSUE TITLE
Arduino TaikoController Compiler Error

### ISSUE THREAD

**Issue by pulipopu** [LuiCat/ArduinoTaikoController#2]
Arduino:1.8.9 (Windows 7), Development board："Arduino Leonardo"

Error reading file (D:\Arduino\hardware\arduino\avr\boards.txt:0): Invalid line format, should be 'key=value'

 Arduino Leonardo Error compiling

**Comment by LuiCat** [comment]
This problem is due to UFT-8-BOM encoding, given that the error is appearing at the beginning of the file. Save the file in ANSI will solve this problem.
![](https://i.loli.net/2019/03/17/5c8e450d56c83.png)
