### ISSUE TITLE
Keyboard doesn't work on Switch ( or i don't know how to setup it because of no instructions about it )

### ISSUE THREAD

**Issue by MinikPLayer** [LuiCat/ArduinoTaikoController#4]
Like in the title, there is no instructions on how to use keyboard mode, and using Keyboard.press or Keyboard.write doesn't seem to work

Controller mode works fine

( using Arduino Pro Micro )

**Comment by LuiCat** [comment]
The instruction in located [in this section](https://github.com/LuiCat/ArduinoTaikoController/blob/master/README.md#keyboard-or-nintndo-switch-controller), but you shouldn't have missed it in the first place. Could

**Comment by MinikPLayer** [comment]
Or i've interpreted it wrong and this doesn't work as Keyboard on NS?

**Comment by LuiCat** [comment]
Keyboard mode won't work for Nintendo Switch at all, since Nintendo Switch is using a non-standard HID protocol rather than the one Arduino library provided. May I ask why do you need the keyboard mode on Switch in your case?

**Comment by MinikPLayer** [comment]
I thought it would work because standard USB keyboards works, i need it to automate some writing in FUZE4 Nintendo Switch

**Comment by LuiCat** [comment]
In this case, you might have to dive into Arduino library to find out if the HID descriptor have any effects on being recognized by Switch. As far as I can tell, there is an "endpoint index" on providing descriptors of all types of devices on the same device. Switch doesn't seems with work with that and assumes the device never send the index. You may have to customize the HID class in Arduino library to fit your needs, in which case you would like to forge a descriptor with both joystick and keyboard input bits.

**Comment by MinikPLayer** [comment]
Thanks for help, i will try!
