### ISSUE TITLE
"state" was not declared in this scope

### ISSUE THREAD

**Issue by asimbulan** [LuiCat/ArduinoTaikoController#8]
In file included from sketch\Joystick.cpp:2:0:
sketch\HIDReportData.h:49:3: warning: #warning Modified LUFA header file. Remove the file if problematic. [-Wcpp]
  #warning Modified LUFA header file. Remove the file if problematic.
   ^~~~~~~
C:\Users\alans\Downloads\ArduinoTaikoController-master\taiko_controller\taiko_controller.ino: In function 'void loop()':
taiko_controller:306:5: error: 'state' was not declared in this scope
     state = 0;
     ^~~~~
C:\Users\alans\Downloads\ArduinoTaikoController-master\taiko_controller\taiko_controller.ino:306:5: note: suggested alternative: 'static'
     state = 0;
     ^~~~~
     static
taiko_controller:308:17: error: 'button_state' was not declared in this scope
       state |= (button_state[i] ? 1 << i : 0);
                 ^~~~~~~~~~~~
taiko_controller:310:20: error: 'hat_mapping' was not declared in this scope
     Joystick.HAT = hat_mapping[state];
                    ^~~~~~~~~~~
exit status 1
'state' was not declared in this scope

**Comment by LuiCat** [comment]
Fixed in the lastest commit.
