### ISSUE TITLE
hat_mapping was not declared in this scope

### ISSUE THREAD

**Issue by asimbulan** [LuiCat/ArduinoTaikoController#9]
Hello again, sorry I do not know how to code.

Arduino: 1.8.13 (Windows 10), Board: "Nintendo Switch Controller (Micro/Leo)"

In file included from sketch\Joystick.cpp:2:0:

sketch\HIDReportData.h:49:3: warning: #warning Modified LUFA header file. Remove the file if problematic. [-Wcpp]

  #warning Modified LUFA header file. Remove the file if problematic.

   ^~~~~~~

C:\Users\alans\Downloads\ArduinoTaikoController-master\taiko_controller\taiko_controller.ino: In function 'void loop()':

taiko_controller:312:20: error: 'hat_mapping' was not declared in this scope

     Joystick.HAT = hat_mapping[state];

                    ^~~~~~~~~~~

taiko_controller:312:32: error: 'state' was not declared in this scope

     Joystick.HAT = hat_mapping[state];

                                ^~~~~

C:\Users\alans\Downloads\ArduinoTaikoController-master\taiko_controller\taiko_controller.ino:312:32: note: suggested alternative: 'static'

     Joystick.HAT = hat_mapping[state];

                                ^~~~~

                                static

exit status 1

'hat_mapping' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by LuiCat** [comment]
Hi, I forgot to update on this one. [This commit](https://github.com/LuiCat/ArduinoTaikoController/commit/a301c7d86bac598aab4b0e787841b96af0503f42) should have fixed your problem. Please reopen if this doesn't work for you.

**Comment by loeldeleon** [comment]
Hey, so I've tried uploading the code found on the front page as well as copy pasting the code found on the Jan 4 commit. Either way I still end up with the error below when trying to use Switch controller mode. Other than modifying the two HID files in the avr folder and the boards.txt file is there anything else I need to do in regards to libraries? Thanks

`C:\Users\Limea\Desktop\ArduinoTaikoController-master\taiko_controller__my_edit_\taiko_controller__my_edit_.ino: In function 'void loop()':
taiko_controller__my_edit_:312:20: error: 'hat_mapping' was not declared in this scope
     Joystick.HAT = hat_mapping[state];
                    ^~~~~~~~~~~
taiko_controller__my_edit_:312:32: error: 'state' was not declared in this scope
     Joystick.HAT = hat_mapping[state];
                                ^~~~~
C:\Users\Limea\Desktop\ArduinoTaikoController-master\taiko_controller__my_edit_\taiko_controller__my_edit_.ino:312:32: note: suggested alternative: 'static'
     Joystick.HAT = hat_mapping[state];
                                ^~~~~
                                static
exit status 1
'hat_mapping' was not declared in this scope`

**Comment by LuiCat** [comment]
Fixed. Please try again.
